FROM apache/superset

ARG USER
ARG FIRSTNAME
ARG LASTNAME
ARG EMAIL
ARG PASSWORD
ARG SUPERSET_SECRET_KEY

USER root
COPY ./superset/home /app/superset_home
RUN chmod +x /app/superset_home
RUN chown -R superset:superset /app/superset_home

USER superset
RUN superset fab create-admin \
    --username ${USER} \
    --firstname ${FIRSTNAME} \
    --lastname ${LASTNAME} \
    --email ${EMAIL} \
    --password ${PASSWORD}

RUN superset db upgrade
RUN superset init
