version: "3.1"

services:
  postgres:
    image: postgres:13.11-bullseye
    container_name: postgres
    restart: on-failure
    ports:
      - "5431:5431"
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: dbt
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dbt_project:/usr/app/
      - ./data:/usr/app/seeds/

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
      args:
        - USER=${SUPERSET_USER}
        - FIRSTNAME=${SUPERSET_FIRSTNAME}
        - LASTNAME=${SUPERSET_LASTNAME}
        - EMAIL=${SUPERSET_EMAIL}
        - PASSWORD=${SUPERSET_PASSWORD}
        - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    container_name: superset
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - 8081:8080
      - 8088:8088
    env_file:
      - .env
    links:
      - postgres:postgres

volumes:
  postgres:
    driver: local

networks:
  backend: {}
