version: '3.1'

services:

  postgres:
    image: postgres:13.11-bullseye
    container_name: postgres
    restart: on-failure
    ports:
      - "5431:5431"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./data:/tmp/data
      # - ./scripts:/tmp/scripts

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env

  dbt:
    build: .
    container_name: dbt
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - ./dbt_project:/usr/app/
      - ./logs:/usr/app/logs
      # - /home/lukas/repositories/dbt=/usr/app
      - /home/lukas/repositories/dbt/profiles.yml=/root/.dbt/

volumes:
  postgres:

networks:
  backend: {}
