version: "3.1"

services:
  postgres:
    image: postgres:13.11-bullseye
    container_name: postgres
    restart: on-failure
    ports:
      - "5431:5431"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: dbt
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dbt_project:/usr/app/
      - ./data:/usr/app/seeds/

volumes:
  postgres:

networks:
  backend: {}
