# profiles.yml
dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 2
      host: "postgres"
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "raw"

    prod:
      type: postgres
      threads: 4
      host: "postgres"
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "raw"

  target: dev
