# profiles.yml
dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 2
      host: "postgres"
      port: 5432
      user: "lukas"
      pass: "senha"
      dbname: "lukas"
      schema: "test"

    prod:
      type: postgres
      threads: 2
      host: "postgres"
      port: 5432
      user: "lukas"
      pass: "senha"
      dbname: "lukas"
      schema: "test"

  target: dev
